services:
  fluentd:
    image: fluent/fluentd:latest
    container_name: fluentd
    ports:
      - "24224:24224"  # Fluentd Forward input
      - "5140:5140"    # Syslog input
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf:ro  # Mount your Fluentd config
      - ./log:/fluentd/log                         # Mount directory for Fluentd logs
      - ./data:/fluentd/data                       # Optional: Persistent data directory
    environment:
      - FLUENT_ELASTICSEARCH_HOST=elasticsearch
      - FLUENT_ELASTICSEARCH_PORT=9200
    restart: always
    networks:
      - logging

networks:
  logging:
    driver: bridge
