services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token # Replace with a secure token in production
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200" # Dev mode listens on all interfaces
    volumes:
      - vault-data:/vault/data
    command: >
      vault server -dev
    restart: unless-stopped

volumes:
  vault-data:
