services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    ports:
      - "2020:2020" # HTTP Server Port (if enabled)
      - "24224:24224" # Fluentd Forward input
      - "5140:5140" # Syslog input
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
    environment:
      - FLUENT_ELASTICSEARCH_HOST=elasticsearch
      - FLUENT_ELASTICSEARCH_PORT=9200
    restart: always
    networks:
      - logging

networks:
  logging:
    driver: bridge