services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform-container
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
    entrypoint: ["/bin/sh", "-c"]
    stdin_open: true
    tty: true