services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0 # Update to the desired version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Ensures the JVM locks memory
      - xpack.security.enabled=false # Disables security (for development purposes)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # Elasticsearch HTTP API
      - "9300:9300" # Transport node-to-node communication
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data # Persistent data storage

volumes:
  elasticsearch_data:
    driver: local
