jenkins:
  systemMessage: "Welcome to Jenkins configured with Docker Compose!"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true

unclassified:
  location:
    url: http://localhost:8080/
    adminAddress: "admin@localhost"

tool:
  git:
    installations:
      - name: "Default Git"
        home: "/usr/bin/git"

