services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent to master communication
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent Jenkins data
      - ./config/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml:ro # Configuration as Code
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    restart: always

volumes:
  jenkins_home:
