services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - minio_network

  # Optional: Create buckets and users on startup
  createbuckets:
    image: minio/mc
    container_name: minio_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin} &&
      mc mb --ignore-existing myminio/bucket1 &&
      mc mb --ignore-existing myminio/bucket2 &&
      mc policy set public myminio/bucket1 &&
      exit 0;
      "
    networks:
      - minio_network

volumes:
  minio_data:

networks:
  minio_network:
    driver: bridge