apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: default
data:
  sentinel.conf: |
    # Name of the monitored master
    sentinel monitor mymaster redis-0.redis.default.svc.cluster.local 6379 2

    # Down-after-milliseconds: How long (in ms) a master or replica needs to be unreachable before it is marked as down
    sentinel down-after-milliseconds mymaster 5000

    # Failover timeout: Maximum time (in ms) to wait for a failover to complete
    sentinel failover-timeout mymaster 10000

    # Parallel syncs: Number of replicas that can be re-synchronized in parallel
    sentinel parallel-syncs mymaster 1

    # Notification script (optional): Script to run when a failover occurs (set a placeholder or remove if unused)
    # sentinel notification-script mymaster /path/to/notification-script.sh

    # Client reconfiguration script (optional): Script to inform clients about the new master (set a placeholder or remove if unused)
    # sentinel client-reconfig-script mymaster /path/to/reconfig-script.sh
