apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: redis:latest
        command: ["redis-sentinel"]
        args: ["/redis-sentinel/sentinel.conf"]
        ports:
        - containerPort: 26379
        volumeMounts:
        - name: config
          mountPath: /redis-sentinel
      volumes:
      - name: config
        configMap:
          name: redis-sentinel-config